# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
#sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1a0dc0f3-eaf7-418d-a085-fa8dbe09bed4
env:
  global:
    - CODECOV_TOKEN='1a0dc0f3-eaf7-418d-a085-fa8dbe09bed4'
# Отправлять уведомление на почту alexmur07@mail.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - alexmur07@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
